from lida import Manager
from lida.datamodel import Goal
import altair as alt
import pandas as pd

lida_manager = Manager(llm=False)  # disables LLM dependency

def generate_lida_charts(df, user_prompt):
    dataset_id = "user_data"
    lida_manager.add_data(name=dataset_id, data=df)

    try:
        goals = lida_manager.goals(name=dataset_id, user_input=user_prompt)
        if not goals:
            return None, "⚠️ LIDA couldn't generate a visualization goal."

        # Generate chart from first goal (no LLM used)
        chart_code = lida_manager.visualize(name=dataset_id, goal=goals[0])
        if chart_code:
            chart = alt.Chart.from_dict(chart_code["chart_spec"])
            summary = goals[0].description or "Generated by LIDA."
            return chart, summary
        else:
            return None, "⚠️ LIDA couldn't generate chart spec."
    except Exception as e:
        return None, f"❌ LIDA Error: {e}"

